package frontEnd;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import java.awt.Dimension;
import java.awt.Insets;

/**
 * Created by mpetuska on November 2017
 */
public class MainForm
{
	private JPanel mainPanel;
	private JTabbedPane tabbedPane1;
	private JButton newButton;
	private JButton deleteButton;
	private JButton editButton;
	private JButton addButton;
	private JButton editButton1;
	private JButton deleteButton1;
	private JButton openEditorButton;
	private JList list1;
	private JList list2;
	private JList list3;
	private JButton newButton1;
	private JButton deleteButton2;
	private JButton editButton2;
	private JButton addButton1;
	private JButton editButton4;
	private JButton removeButton;
	private JButton openEditorButton1;
	private JList list4;
	private JList list5;
	private JList list6;
	
	public JPanel getMainPanel()
	{
		return mainPanel;
	}
	
	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}
	
	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		mainPanel = new JPanel();
		mainPanel.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1,
						-1));
		tabbedPane1 = new JTabbedPane();
		mainPanel.add(tabbedPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null,
				new Dimension(200, 200), null, 0, false));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1,
						-1));
		tabbedPane1.addTab("Rota Evolution", panel1);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1,
						-1));
		tabbedPane1.addTab("Manager Profiles", panel2);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1,
						-1));
		panel2.add(panel3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null,
				null, null, 0, false));
		panel3.setBorder(BorderFactory.createTitledBorder("Profiles"));
		newButton1 = new JButton();
		newButton1.setText("New...");
		panel3.add(newButton1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		deleteButton2 = new JButton();
		deleteButton2.setText("Delete");
		panel3.add(deleteButton2, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		list6 = new JList();
		panel3.add(list6, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null,
				new Dimension(150, 50), null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setText("Count:");
		panel3.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JLabel label2 = new JLabel();
		label2.setText("3");
		panel3.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JPanel panel4 = new JPanel();
		panel4.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1,
						-1));
		panel2.add(panel4, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null,
				null, null, 0, false));
		panel4.setBorder(BorderFactory.createTitledBorder("Details"));
		editButton2 = new JButton();
		editButton2.setText("Edit...");
		panel4.add(editButton2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		list5 = new JList();
		panel4.add(list5, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null,
				new Dimension(150, 50), null, 0, false));
		final JPanel panel5 = new JPanel();
		panel5.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1,
						-1));
		panel2.add(panel5, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null,
				null, null, 0, false));
		panel5.setBorder(BorderFactory.createTitledBorder("Demand"));
		addButton1 = new JButton();
		addButton1.setText("Add...");
		panel5.add(addButton1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		editButton4 = new JButton();
		editButton4.setText("Edit...");
		panel5.add(editButton4, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		removeButton = new JButton();
		removeButton.setText("Remove");
		panel5.add(removeButton, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		openEditorButton1 = new JButton();
		openEditorButton1.setText("Open Editor");
		panel5.add(openEditorButton1, new com.intellij.uiDesigner.core.GridConstraints(2, 3, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		list4 = new JList();
		panel5.add(list4, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 4,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null,
				new Dimension(150, 50), null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setText("Total:");
		panel5.add(label3, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JLabel label4 = new JLabel();
		label4.setText("150 h");
		panel5.add(label4, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JLabel label5 = new JLabel();
		label5.setText("Daily Average:");
		panel5.add(label5, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JLabel label6 = new JLabel();
		label6.setText("20 h/d");
		panel5.add(label6, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JPanel panel6 = new JPanel();
		panel6.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1,
						-1));
		tabbedPane1.addTab("Employee Profiles", panel6);
		final JPanel panel7 = new JPanel();
		panel7.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1,
						-1));
		panel6.add(panel7, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null,
				null, null, 0, false));
		panel7.setBorder(BorderFactory.createTitledBorder("Employees"));
		newButton = new JButton();
		newButton.setText("New...");
		panel7.add(newButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		deleteButton = new JButton();
		deleteButton.setText("Delete");
		panel7.add(deleteButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		list1 = new JList();
		panel7.add(list1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null,
				new Dimension(150, 50), null, 0, false));
		final JLabel label7 = new JLabel();
		label7.setText("Count:");
		panel7.add(label7, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JLabel label8 = new JLabel();
		label8.setText("0");
		panel7.add(label8, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JPanel panel8 = new JPanel();
		panel8.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1,
						-1));
		panel6.add(panel8, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null,
				null, null, 0, false));
		panel8.setBorder(BorderFactory.createTitledBorder("Details"));
		editButton = new JButton();
		editButton.setText("Edit...");
		panel8.add(editButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		list2 = new JList();
		panel8.add(list2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null,
				new Dimension(150, 50), null, 0, false));
		final JPanel panel9 = new JPanel();
		panel9.setLayout(
				new com.intellij.uiDesigner.core.GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1,
						-1));
		panel6.add(panel9, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null,
				null, null, 0, false));
		panel9.setBorder(BorderFactory.createTitledBorder("Availability"));
		addButton = new JButton();
		addButton.setText("Add...");
		panel9.add(addButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		editButton1 = new JButton();
		editButton1.setText("Edit...");
		panel9.add(editButton1, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		deleteButton1 = new JButton();
		deleteButton1.setText("Delete");
		panel9.add(deleteButton1, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		openEditorButton = new JButton();
		openEditorButton.setText("Open Editor");
		panel9.add(openEditorButton, new com.intellij.uiDesigner.core.GridConstraints(2, 3, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
						| com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		list3 = new JList();
		panel9.add(list3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 4,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null,
				new Dimension(150, 50), null, 0, false));
		final JLabel label9 = new JLabel();
		label9.setText("Total:");
		panel9.add(label9, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JLabel label10 = new JLabel();
		label10.setText("40 h");
		panel9.add(label10, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
		final JLabel label11 = new JLabel();
		label11.setText("Daily Average:");
		panel9.add(label11, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1,
				false));
		final JLabel label12 = new JLabel();
		label12.setText("4.5 h/d");
		panel9.add(label12, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
				false));
	}
	
	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return mainPanel;
	}
}
